"""
plot_clusters.py

Reads `output.txt` generated by the K-Means C++ program, parses the final clusters,
creates a combined plot (saved by default as `graph.png`) and writes a cluster summary
table (Markdown or CSV).

Usage:
    python plot_clusters.py output.txt                    # create graph.png and clusters.md
    python plot_clusters.py output.txt -d 1 --out-image g.png --table-out clusters.csv --table-format csv --show

Dependencies:
    matplotlib, numpy
    Install with: pip install matplotlib numpy
"""

import re
import argparse
import matplotlib.pyplot as plt
import numpy as np
import sys


def parse_output_file(path):
    """Parse the output file and return a list of datasets.
    Each dataset is a list of clusters; each cluster is a dict:
        {'centroid': [f1, f2, ...], 'members': [[f1,f2,...], ...]}
    """
    with open(path, 'r') as f:
        lines = [ln.strip() for ln in f.readlines()]

    datasets = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith('Dataset'):
            # move forward until we find "Final Clusters after Convergence:"
            i += 1
            while i < len(lines) and 'Final Clusters after Convergence' not in lines[i]:
                i += 1
            if i >= len(lines):
                break
            # now parse clusters
            i += 1
            clusters = []
            while i < len(lines):
                if lines[i].startswith('Cluster'):
                    # extract centroid
                    centroid_line = lines[i]
                    m = re.search(r'Centroid:\s*([^\)]+)\)', centroid_line)
                    centroid = []
                    if m:
                        centroid = [float(x) for x in m.group(1).split() if x.strip()]
                    # next line should be Members:
                    members = []
                    if i+1 < len(lines) and lines[i+1].startswith('Members:'):
                        memline = lines[i+1]
                        # find all occurrences like `(2.00 20.00 )` or `(2.00 )`
                        groups = re.findall(r'\(([^\)]+)\)', memline)
                        for g in groups:
                            vals = [float(x) for x in g.split() if x.strip()]
                            members.append(vals)
                        i += 2
                    else:
                        i += 1
                    clusters.append({'centroid': centroid, 'members': members})
                else:
                    break
            datasets.append(clusters)
        else:
            i += 1
    return datasets


def write_table(datasets, path, fmt='md'):
    """Write a summary table for all datasets.
    fmt: 'md' for Markdown, 'csv' for CSV
    """
    lines = []
    if fmt == 'md':
        for di, clusters in enumerate(datasets, start=1):
            lines.append(f"## Dataset {di}\n")
            lines.append('| Cluster | Centroid | Members |')
            lines.append('|---|---:|---|')
            for ci, c in enumerate(clusters, start=1):
                cent = ', '.join([str(round(x, 4)) for x in c['centroid']]) if c['centroid'] else ''
                mems = '; '.join(['(' + ', '.join([str(round(x,4)) for x in m]) + ')' for m in c['members']])
                lines.append(f'| {ci} | {cent} | {mems} |')
            lines.append('\n')
    elif fmt == 'csv':
        lines.append('dataset,cluster,centroid,members')
        for di, clusters in enumerate(datasets, start=1):
            for ci, c in enumerate(clusters, start=1):
                cent = ' '.join([str(round(x, 6)) for x in c['centroid']]) if c['centroid'] else ''
                mems = ' | '.join([' '.join([str(round(x,6)) for x in m]) for m in c['members']])
                lines.append(f'{di},{ci},"{cent}","{mems}"')
    else:
        raise ValueError('Unsupported format')

    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f"Saved cluster table to {path}")


def create_combined_plot(datasets, out_image='graph.png', show=False):
    """Create a single image with subplots for each dataset and save as out_image."""
    n = len(datasets)
    if n == 0:
        print('No datasets to plot')
        return

    # choose grid layout
    cols = 1 if n == 1 else 1
    rows = n
    fig, axes = plt.subplots(rows, cols, figsize=(7 * cols, 4 * rows))
    if n == 1:
        axes = [axes]
    else:
        axes = axes.flatten()

    colors = plt.cm.tab10.colors

    for idx, (ax, clusters) in enumerate(zip(axes, datasets), start=1):
        # determine dimension
        dim = None
        for c in clusters:
            if c['members']:
                dim = len(c['members'][0])
                break
        if dim is None:
            for c in clusters:
                if c['centroid']:
                    dim = len(c['centroid'])
                    break
        if dim is None:
            ax.text(0.5, 0.5, 'Unknown dimensionality', ha='center')
            continue

        if dim == 1:
            for k, c in enumerate(clusters):
                xs = [m[0] for m in c['members']] if c['members'] else []
                ys = np.random.normal(loc=k * 0.2, scale=0.02, size=len(xs)) if xs else []
                ax.scatter(xs, ys, color=colors[k % len(colors)], label=f'Cluster {k+1}', alpha=0.8)
                if c['centroid']:
                    cx = c['centroid'][0]
                    ax.scatter([cx], [k * 0.2], marker='X', s=100, color='k')
                    ax.text(cx, k * 0.2 + 0.03, f"C{k}={round(cx,4)}", ha='center')
            ax.get_yaxis().set_visible(False)
            ax.set_xlabel('Value')
            ax.set_title(f'Dataset {idx} - 1D clusters')
            ax.legend()

        elif dim == 2:
            for k, c in enumerate(clusters):
                xs = [m[0] for m in c['members']] if c['members'] else []
                ys = [m[1] for m in c['members']] if c['members'] else []
                ax.scatter(xs, ys, color=colors[k % len(colors)], label=f'Cluster {k+1}', alpha=0.8)
                if c['centroid']:
                    cx, cy = c['centroid'][0], c['centroid'][1]
                    ax.scatter([cx], [cy], marker='X', s=120, color='k')
                    ax.text(cx, cy, f"  C{k+1}({round(cx,2)}, {round(cy,2)})", fontsize=9)
            ax.set_xlabel('X')
            ax.set_ylabel('Y')
            ax.set_title(f'Dataset {idx} - 2D clusters')
            ax.legend()
            ax.grid(True, linestyle='--', alpha=0.4)

        else:
            ax.text(0.5, 0.5, f'{dim}D plotting not supported', ha='center')
            ax.set_title(f'Dataset {idx}')

    plt.tight_layout()
    plt.savefig(out_image, dpi=150)
    print(f"Saved combined plot to {out_image}")
    if show:
        plt.show()
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description='Plot clusters parsed from output.txt')
    parser.add_argument('file', help='Path to output.txt')
    parser.add_argument('-d', '--dataset', type=int, default=0, help='Dataset index to plot (1-based). 0=all')
    parser.add_argument('--show', action='store_true', help='Show plot interactively')
    parser.add_argument('--out-image', default='graph.png', help='Output combined image filename')
    parser.add_argument('--table-out', default='clusters.md', help='Output table filename (Markdown or CSV)')
    parser.add_argument('--table-format', choices=['md', 'csv'], default='md', help='Format for table output')

    args = parser.parse_args()

    datasets = parse_output_file(args.file)
    if not datasets:
        print('No datasets found in file.')
        sys.exit(1)

    # optionally select a single dataset
    if args.dataset <= 0:
        selected = datasets
    else:
        idx = args.dataset
        if idx < 1 or idx > len(datasets):
            print(f'Dataset index out of range (1..{len(datasets)})')
            sys.exit(1)
        selected = [datasets[idx-1]]

    write_table(selected, args.table_out, fmt=args.table_format)
    create_combined_plot(selected, out_image=args.out_image, show=args.show)


if __name__ == '__main__':
    main()
